server.port: 8888

spring.cloud.config.server.git.uri: https://github.com/devs4j/microservices-config
spring.cloud.config.server.git.searchPaths: menu
spring.cloud.config.server.git.username: devs4j
spring.cloud.config.server.git.password: h0l41234!

spring.security.user.name: user
spring.security.user.password: password